# Only strict vX.Y.Z tags are used; tag names are spliced into shell and Python code below.
all_versions := `git tag --list 'v*' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | tr '\n' ' '`
latest_version := `git describe --tags --match='v*' --exclude='*[!v0-9.]*'`

build := "target"
path_javadoc := "javadoc"
latest_version_name := "current"

repo TAG:
  @{{ if TAG =~ '^(v[0-9]+\.[0-9]+\.[0-9]+|current)$' { "true" } else { "echo 'invalid tag' >&2; false" } }}
  rm -rf '{{build}}/repo/lz4-java-{{TAG}}'
  mkdir -p '{{build}}/repo'
  if [ '{{TAG}}' = '{{latest_version_name}}' ]; then ln -s ../../.. '{{build}}/repo/lz4-java-{{TAG}}'; else git clone --shared --branch='{{TAG}}' .. '{{build}}/repo/lz4-java-{{TAG}}'; fi

template NAME TAG: (repo TAG)
  #!/usr/bin/env -S uv run --script
  # /// script
  # requires-python = ">=3.12"
  # dependencies = [
  #   "semver",
  #   "mistune",
  #   "pygments",
  #   "Jinja2"
  # ]
  # ///
  import semver
  import mistune
  import os
  import re
  import pygments
  import pygments.lexers
  import pygments.formatters
  from jinja2 import Environment, FileSystemLoader, select_autoescape
  env = Environment(loader=FileSystemLoader("."), autoescape=True)

  semantic_versions = '{{all_versions}}'.split()
  semantic_versions.sort(reverse=True, key=lambda v: semver.VersionInfo.parse(v[1:]))

  selected_version_actual = '{{TAG}}' if '{{TAG}}' != '{{latest_version_name}}' else '{{latest_version}}'

  def readme_source():
    text = open('{{build}}/repo/lz4-java-{{TAG}}/README.md').read()
    if '{{TAG}}' != '{{latest_version_name}}':
      # The README badges show the state of the main branch. On pages for older versions, pin the Maven Central badge to
      # that version and drop the others.
      version = '{{TAG}}'[1:]
      text = re.sub(
          r'^\[!\[Maven Central\]\(https://img\.shields\.io/maven-central/v/([^/)]+)/([^/)]+)\)\]\([^)]*\)$',
          lambda m: f'[![Maven Central](https://img.shields.io/badge/maven--central-v{version}-blue)]'
                    f'(https://central.sonatype.com/artifact/{m[1]}/{m[2]}/{version})',
          text, flags=re.M)
      text = re.sub(r'^\[!\[(?!Maven Central\]).*\n', '', text, flags=re.M)
    return text

  html_formatter = pygments.formatters.HtmlFormatter()
  class PygmentsRenderer(mistune.HTMLRenderer):
    def block_code(self, code, info=None):
      if info:
        lang = info.split(None, 1)[0]
      else:
        lang = None
      if lang:
        return pygments.highlight(code, pygments.lexers.get_lexer_by_name(lang), html_formatter)
      else:
        return super().block_code(code, lang)

  try:
    os.makedirs('{{build}}/templates/{{TAG}}')
  except:
    pass
  with open('{{build}}/templates/{{TAG}}/{{ NAME }}', 'w') as f:
    f.write(env.get_template("{{ NAME }}.jinja").render(
        all_versions=semantic_versions,
        latest_version='{{latest_version}}',
        latest_version_name='{{latest_version_name}}',
        selected_version='{{TAG}}',
        selected_version_actual=selected_version_actual,
        path_javadoc='{{path_javadoc}}',
        readme=lambda: mistune.create_markdown(renderer=PygmentsRenderer(), plugins=['table'])(readme_source()),
        pygments_style=lambda: html_formatter.get_style_defs()
        ))

#[arg('TAG', pattern='v\d+\.\d+\.\d+')]
javadoc TAG: (template "header-javadoc.html" TAG)
  header=$(cat '{{build}}/templates/{{TAG}}/header-javadoc.html') && cd '{{build}}/repo/lz4-java-{{TAG}}' && ./mvnw javadoc:javadoc "-Dheader=$header"
  mkdir -p '{{build}}/site/{{TAG}}'
  cp -rf '{{build}}/repo/lz4-java-{{TAG}}/target/site/apidocs' '{{build}}/site/{{TAG}}/{{path_javadoc}}'

version TAG: (javadoc TAG) (template "index.html" TAG)
  cp -f '{{build}}/templates/{{TAG}}/index.html' '{{build}}/site/{{TAG}}/index.html'

rewrite-version-links:
  #!/usr/bin/env -S uv run --script
  # /// script
  # requires-python = ">=3.12"
  # ///
  import pathlib

  root = pathlib.Path("target/site")
  for p in root.glob("**/*.html"):
    to_root = root.relative_to(p.parent, walk_up=True)

    html = p.read_text()
    for v in ['{{latest_version_name}}'] + '{{all_versions}}'.split():
      # walk up to root, enter the new version, then walk back down to same path.
      new_parts = [*to_root.parts, v, *p.relative_to(root).parts[1:]]
      if new_parts[-1] == 'index.html':
        new_parts[-1] = ''
      html = html.replace('REWRITE_PATH_' + v, str(pathlib.Path(*new_parts)))
    if '{{path_javadoc}}' in p.relative_to(root).parts:
      html = html.replace('</title>', '</title><link rel="stylesheet" href="' + str(to_root) + '/common.css"><link rel="stylesheet" href="' + str(to_root) + '/javadoc.css">')
    p.write_text(html)

# Publish the JaCoCo report of the working tree, if it was built with `./mvnw -Pcoverage verify`
coverage:
  if [ -f ../target/site/jacoco/jacoco.csv ]; then \
    cp -r ../target/site/jacoco '{{build}}/site/{{latest_version_name}}/coverage' && \
    python3 ../scripts/jacoco_summary.py ../target/site/jacoco/jacoco.csv --badge '{{build}}/site/{{latest_version_name}}/coverage/badge.json'; \
  fi

prepare:
  rm -rf '{{build}}/site'
  mkdir -p '{{build}}/site'
  ln -s ../../javadoc.css ../../common.css ../../markdown.css ../../_redirects '{{build}}/site'

log:
  @echo "Available tags: {{all_versions}}"
  @echo "Current tag: {{latest_version}}"

all: log prepare (version latest_version_name) && coverage rewrite-version-links
  set -e; for v in {{all_versions}}; do just 'all_versions={{all_versions}}' 'latest_version={{latest_version}}' version "$v"; done
