name: Run tests

on:
  push:
  pull_request:

jobs:
  linux:
    name: Linux test
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-24.04
          - runs-on: ubuntu-24.04-arm
            # Azul Zulu 7 not available on Aarch64
            maven-flags: >-
              -Dmaven.compiler.source=8
              -Dmaven.compiler.target=8
          - runs-on: ubuntu-24.04-riscv
            # Disable fuzzing until https://github.com/CodeIntelligenceTesting/jazzer supports linux-riscv64
            maven-flags: >-
              -Dtest='!net/jpountz/fuzz/*'
              -Dmaven.compiler.source=8
              -Dmaven.compiler.target=8
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Zulu JDK 7
        if: matrix.runs-on == 'ubuntu-24.04'
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: zulu
          java-version: '7'
      - name: Setup Temurin JDK 25
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven
      - name: Build (mvn verify)
        run: |
          if [ $(uname -m) = "x86_64" ]; then
            arch_id=amd64
          else
            arch_id=$(uname -m)
          fi
          ./mvnw -B -ntp -V \
            -Darch.id=${arch_id} \
            -Dnative.cc=gcc \
            -Dsurefire.reportFormat=plain \
            ${{ matrix.maven-flags }} \
            verify
